### ISSUE TITLE
Configuration files order

### ISSUE THREAD

**Issue by bestlibre** [ogarcia/trellowarrior#11]
`RawConfigParser.read([file1, file2, ...])` try to read all the files given as argument and override the conf values with the last read.

The order of the configuration file list is important and it should be clear to the user that a merge will occur. If a merge is not intended, it's easy to fix (I can create the PR later).

In all cases, what is the order of priority for the conf files ? I'm in favor of (by increasing priority) : 

- ~/.config/trellowarrior/trellowarrior.conf
- ~/.trellowarrior.conf
- ./trellowarrior.conf

**Comment by ogarcia** [comment]
Agree. I see it right.

* ~/.config/trellowarrior/trellowarrior.conf
* ~/.trellowarrior.conf
* ./trellowarrior.conf
* Path given by user with `-c` or `--config`.

**Comment by bestlibre** [comment]
I have fixed the read order in a new branch. What about the merge ?

**Comment by ogarcia** [comment]
Done!

**Comment by bestlibre** [comment]
I was speaking of the merge of the configuration files ;)

If the list is given to confparser.read and multiple files exist, the result will be a merge of all the existing files. I think it is cleaner to pick the first existing one, without merging.

**Comment by ogarcia** [comment]
Yes, the best is pick the first one and not merge it.
