### ISSUE TITLE
trellowarrior.py: error: unrecognized arguments: --trello-name

### ISSUE THREAD

**Issue by MarshCastle** [ogarcia/trellowarrior#16]
I'm getting this on install:
```
trellowarrior.py: error: unrecognized arguments: --trello-name xxx
```
using the line given from the docs:
```
trellowarrior.py -c path/to/your/configfile authenticate --api-key your_api_key --api-key-secret your_api_secret --trello-name TrelloWarrior --expiration 30days

```
 ...is there something I could have done wrong?

I cloned the project locally and have installed both of the python libraries. API Keys should be good (they came from Trello - as suggested).

I'm running Debian Buster.

**Comment by ogarcia** [comment]
Is a typo in docs, use `--name` :wink:
