### ISSUE TITLE
Help with `sync_projects` to run `trellowarrior sync`

### ISSUE THREAD

**Issue by santiyounger** [ogarcia/trellowarrior#21]
Hey, 
Thanks for the amazing work with this project. I'm really excited to get it going.

I'm on Arch Linux

I installed trellowarrior through the AUR successfully

Right now I'm setting everything up, the whole API setup was super clear thanks for the clean instructions.

I got everything regarding the API working

## Issues with Mandatory Fields after sync_projects
I only run into a problem with running the initial `trellowarrior sync`

There's  something I'm not setting correctly in the last MANDATORY FIELDS

`sync_projects`
Can I have more info please on how to fill-up this field? What is meant by ` Define what sections are loaded, `
```
sync_projects MANDATORY. Define what sections are loaded, separated by spaces.
```
Then I filled up these ones
```
taskwarrior_project_name MANDATORY. The name of project in Taskwarrior.
trello_board_name MANDATORY. The name of Trello Board.
```
My trello bard is called "TODO"
so I put this in my  trellowarrior.conf
which was by defauly created in:
~/.config/trellowarrior/trellowarrior.conf

```
taskwarrior_project_name = TODO
trello_board_name = TODO
```

## Should the task warrior project name be the same?

overall this is what my trellowarrior.conf looks like

```bash
trello_api_key = ********************************
trello_api_secret = ****************************************************************
trello_token = ****************************************************************
trello_token_secret = ********************************
sync_projects
taskwarrior_project_name = TODO
trello_board_name = TODO
```

## This is the error I get 
```
┗━━━━━━  trellowarrior sync
Traceback (most recent call last):
  File "/usr/bin/trellowarrior", line 33, in <module>
    sys.exit(load_entry_point('trellowarrior==1.2.1', 'console_scripts', 'trellowarrior')())
  File "/usr/lib/python3.8/site-packages/trellowarrior/main.py", line 128, in main
    config.configure(config_file=args.config, projects=args.projects)
  File "/usr/lib/python3.8/site-packages/trellowarrior/config.py", line 62, in configure
    config_parser.read(self.config_file)
  File "/usr/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.8/configparser.py", line 1113, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/home/santi/.config/trellowarrior/trellowarrior.conf'
	[line  6]: 'sync_projects\n'
```

I'm sure I'm using `sync_projects` wrong I just need some direction on how to do it correctly and some help to see if there's anything else I'm missing.

## Specs
Linux Manjaro XFCE with Awesome Window Manager

Thanks for the help!

**Comment by ogarcia** [comment]
Hi Santi,

The main problem is that you are not defining a section in your config. If you look the [example config file](https://github.com/ogarcia/trellowarrior/blob/master/trellowarrior.conf) you will understand it.

Anyway, your config file must be:
```
[DEFAULT]
trello_api_key = ********************************
trello_api_secret = ****************************************************************
trello_token = ****************************************************************
trello_token_secret = ********************************
sync_projects = my_todo

[my_todo]
taskwarrior_project_name = TODO
trello_board_name = TODO
```

The name of section `my_todo` is arbitrary, you can use any word.

Tell me if this solve your question :wink:

**Comment by santiyounger** [comment]
Thank you so much @ogarcia that solves it. I didn't see there was an [example config](https://github.com/ogarcia/trellowarrior/blob/master/trellowarrior.conf) My bad for not checking.

 I'd suggest, it might be really useful to add a link to  the example trellowarrior.conf in the README.md for other beginners struggiling with that final step.

Really appreciate the help, can't wait to start using trellowarrior everyday, thank you for your hard work!

**Comment by ogarcia** [comment]
> I'd suggest, it might be really useful to add a link to the example trellowarrior.conf in the README.md for other beginners struggiling with that final step.

The first paragraph in [Configuration section of README.md](https://github.com/ogarcia/trellowarrior#configuration) says:
The TrelloWarrior config is very easy. There is a `trellowarrior.conf` sample file that you can modify to set with your data.

:joy: :joy: :joy: :joy:

**Comment by santiyounger** [comment]
I don't know how I missed that! thanks. Sound good, thanks again for the help. Excellent project, have been really making the most of it!
