### ISSUE TITLE
2 computers with trello questions, current setbacks

### ISSUE THREAD

**Issue by santiyounger** [ogarcia/trellowarrior#22]
I've just set up trello warrior to work from my linux laptop and my iMac.

This way I can sink them both to be indenticual and sync everything with the same trelloboard.

after making changes in my iMac and doing `trellowarrior sync` I move to my Linux laptop and once I do `trellowarrior sync`

I get the following
```
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.trello.com', port=443): Max retries exceeded with url: /1/members/me/boards/?filter=open (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7ce3078ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```
I've also gotten
````
  File "/usr/lib/python3.8/site-packages/trello/trelloclient.py", line 231, in fetch_json
    raise ResourceUnavailable("%s at %s" % (response.text, url), response)
trello.exceptions.ResourceUnavailable: {"message":"Rate limit exceeded: requests per interval for API token","error":"API_TOKEN_LIMIT_EXCEEDED"} at https://api.trello.com/1/cards/********************* (HTTP status: 429)
````
If I open that link to api.trello.com I get this
![image](https://user-images.githubusercontent.com/51902730/102361632-715a3380-3f81-11eb-9907-0e8b0a67ac29.png)

Is there anyway to search what card it is? Either in trello, or with task warrior, since it's not a taskwarrior ID I can not easily search it, to see if that specific card is causing conflicts.

For both oth this errors, If I try again after 1 minute or 2 `trellowarrior sync` works again correctly.

---
## Some tasks not showing in tasks' count 

After this the only issue I can't figure out why is task count is not showing, I'm not sure if some tasks were not synced

 I use [VIT](https://github.com/vit-project/vit) to visualize my tasks and edit them
 
---

when I go to `next` in my Linux laptop (the first computer where I set up all of my tasks) I have 
`177 tasks shown`

after a `trellowarrior sync` 

my imac shows

`159 tasks shown`

I can't figure out what are the missing tasks, nor do I get an error after sync, is there anything I'm missing.

---

I made the set up in my imac exactly the same as my linux set up. I copied the exact same api numbers, is this correct?

Please, let me know if there's any part of the process I'm missing, to have the exact same setup in both computer and in trello.

Thank you

**Comment by ogarcia** [comment]
The 401 error is an external problem. The API of trello was offline for a problem in Trello servers. In this case trellowarrior gives you the ConnectionError/ResourceUnavailable and does nothing.

If you have different number of taks maybe you has not all taks in same project and some of them are out of sync.

**Comment by santiyounger** [comment]
got you, thanks for the info of trello's API that makes sense since after trying again after a couple minutes the sync works.

I only have one project, but I'll try to identify if some cards have some syncing error, which I think it might be the case.

If I identify an error with trello warrior regarding tasks counts I might open a new issue, for now I'll close this.

Thanks for your help!
