### ISSUE TITLE
Multiple "doing" lists?

### ISSUE THREAD

**Issue by tonycpsu** [ogarcia/trellowarrior#23]
I'm interested in support for multiple Trello lists for mapping to the "doing" status that could be differentiated with tags or a suffix to the project name.  Just wondering if this is something that would be precluded or made more difficult by the current design in any way, and, if not, if this is something you'd accept a PR for.

**Comment by ogarcia** [comment]
The main philosophy of the project is _keep it simply_. I think that several lists with _doing_ status can be confusing for many users and can difficult the application setup. Take note that you can have as many lists as you want and you can move tasks between them.

**Comment by tonycpsu** [comment]
Not sure what you mean by "as many lists as you want".  The Trello board in question already has multiple lists representing stages in a task's execution.   On the TaskWarrior end, I'd like these to be synced and distinguishable in some way (e.g. with project name.)

Do you perhaps mean multiple *project* definitions mapped to the same Trello board, each with their own list configuration?

**Comment by ogarcia** [comment]
You have this UDA.
```
uda.trellolistname.type=string
uda.trellolistname.label=Trello List Name
```

This store equivalence between trello list and taskwarrior, if you want to move a task from one list to other simply edit this uda. For example:
```
task add "Paint the door" project:Home trellolistname:"To Do Someday"
```
This add a new task in the list _To Do Someday_ of the project _Home_

And to move to other list (assuming that is the first task)
```
task modify 1 trellolistname:"Doing NOW"
```
Move the task from list _To Do Someday_ to list _Doing NOW_

**Comment by tonycpsu** [comment]
Brilliant!  I didn't know it would sync back to Trello.  That works perfectly for my purposes.  Thank you!
