### ISSUE TITLE
[Q] Daemon synchronisation process

### ISSUE THREAD

**Issue by leikoilja** [ogarcia/trellowarrior#24]
Hey, community.

First of all, thanks for the flawless amazing integration! 
I was wondering if there is any convenient way to keep the synchronization near "real-time" between Trello and taskwarrior? Perhaps some sort of a daemon process?

**Comment by ogarcia** [comment]
You can use system tools for this, for example with a [systemd timer](https://wiki.archlinux.org/index.php/Systemd/Timers)

**Comment by leikoilja** [comment]
Thank you for the advice, @ogarcia.
I have added a cronjob on mac (to sync every 30 minutes from 8am to 6pm):
`*/30 8-18 * * * cd /<FULL-PATH-TO-CRON-JOB-SCRIPTS>/cron_jobs && ./trellowarrior_sync.sh`

To run the `trellowarrior_sync.sh` that looks like this:
```bash
#!/bin/sh
# Cron job that will periodically sync the trello-taskwarrior using python 'trellowarrior' package

# Path to python virtual environment where trellowarrior was installed and configured
<FULL-PATH-TO-PYTHON-DIRECTORY>/bin/python -c 'from trellowarrior.main import main; main()'
```

**Comment by leikoilja** [comment]
With some of @ogarcia help(See https://github.com/ogarcia/trellowarrior/pull/28) I finally managed to setup a cronjob on my mac to sync the tasks automatically every 30 minutes during the workday. 
I have a cronjob set using `crontab -e` that looks like this:
```bash
*/30 8-18 * * * cd /<PATH-TO-DIR>/cron_jobs && ./trellowarrior_sync.sh >> /tmp/stderr.log 2>&1
```
And the script `trellowarrior_sync.sh`: 
```bash
#!/bin/sh

# Cron job that will periodically sync the trello board with taskwarrior
# python 'trellowarrior' package

# Path to the `task` executable. Otherwise, it will through the error in logs that `task`(taskwarrior) is not found
PATH=/usr/local/bin:$PATH
export PATH

# Path to python virtual environment where trellowarrior was installed and configured
/<PATH>/Envs/nvim/bin/trellowarrior --config /<PATH-TO-CONFIG>/.trellowarrior.conf

```
