### ISSUE TITLE
[Feature request] Trello task's link

### ISSUE THREAD

**Issue by leikoilja** [ogarcia/trellowarrior#26]
It would be great to have a link mapping between trellos's card and taskwarrior task.
Perhaps something like this:
On trello: My card (https://trello.com/c/RaBOy722/2-my-card)
On taskwarrior: My card (with an attribute `UDA trellolink: https://trello.com/c/RaBOy722/2-my-card`)

**Comment by danjones1618** [comment]
This could work nicely with [jschlatow/taskopen](https://github.com/jschlatow/taskopen). From a quick look I think you'd need to annotate the task with the URL instead of a UDA.
