### ISSUE TITLE
Unintended new cards on sync 

### ISSUE THREAD

**Issue by nicolas-graves** [ogarcia/trellowarrior#30]
Hi ! Thanks for this amazing piece of software. 

I have a few issues with it though, 

**Expected behaviour** 
On a board, when adding a card, when adding a card and syncing, everything sync properly, and I have the same card / task on both applications. 

**Observed behaviour** 
With each sync, a few new cards are added. The number of cards added is related to the number of cards already present. 

It also seems that my tasks on taskwarrior have a few urls, as if there were no checks of an already present URL / card, and thus the creation of a new card. 

After a few syncs on a blanck board with one task, it looks like that : 
![pic-full-210412-0806-20](https://user-images.githubusercontent.com/76450848/114349019-a1989400-9b67-11eb-96be-209a183f94d7.png)

Here are the contents of such a "created by sync" card on taskwarrior : 

```
# Name               Editable details
# -----------------  ----------------------------------------------------
# ID:                22
# UUID:              xxxxxxxxxxx
# Status:            Pending
# Mask:              
# iMask:             
  Project:           test
# Separate the tags with spaces, like this: tag1 tag2
  Tags:              
  Description:       trellolistname:'A FAIRE'
  Created:           2021-04-12 08:09:46
  Started:           
  Ended:             
  Scheduled:         
  Due:               
  Until:             
  Recur:             
  Wait until:        
# Modified:          2021-04-12 08:10:18
  Parent:            
# Annotations look like this: <date> -- <text> and there can be any number of them.
# The ' -- ' separator between the date and text field should not be removed.
# A "blank slot" for adding an annotation follows for your convenience.
  Annotation:        2021-04-12 08:09:46 -- [Trello URL] https:\/\/trello.com\/c\/azertyuiop
  Annotation:        2021-04-12 08:10:18 -- [Trello URL] https:\/\/trello.com\/c\/lollipop ##they are different cards, with different links. 
  Annotation:        2021-04-12 08:21:56 -- 
# Dependencies should be a comma-separated list of task IDs/UUIDs or ID ranges, with no spaces.
  Dependencies:      
# User Defined Attributes
  UDA priority:      
  UDA trelloid:      
  UDA trellolistname: 
# End
```

**Comment by ogarcia** [comment]
What version of TrelloWarrior are you using?

and

Do you have in your `~/.taskrc` the following config **before** first sync?
```
# Trellowarrior UDAs
uda.trelloid.type=string
uda.trelloid.label=Trello ID
uda.trellolistname.type=string
uda.trellolistname.label=Trello List Name
```

**Comment by nicolas-graves** [comment]
Thanks for the quick answer ! 

1.3.1, I installed trellowarrior this weekend with the AUR. 

Yes I do have these lines in my taskrc, although in `~/.config/task/taskrc` (the `$TASKRC` environmental variable is properly set). And I'm pretty sure I had them before first sync.

The Trellowarrior config for the project in question is this :
```
sync_projects = TEST

[TEST]
taskwarrior_project_name = test
trello_board_name = test de tableau
trello_todo_list = A FAIRE
trello_done_list = MISSIONS ACHEVEES
trello_doing_list = MISSIONS EN COURS
trello_lists_filter = A IGNORER
```

Oh I noticed that I installed other packages (py-trello...) directly from the AUR (with `makepkg -si` and not `yay`), might be coming from there.

**Comment by nicolas-graves** [comment]
Other dependencies : `tasklib-2.3.0` ; `python-py-trello-0.17.1`. 
But they're probably the ones installed with `yay` too.

**Comment by nicolas-graves** [comment]
I took a new look on the problem. 
Seems like `${XDG_CONFIG_HOME}` or `${XDG_DATA_HOME}` are not evaluated in the trellowarrior conf, might just be this.

**Comment by ogarcia** [comment]
> I took a new look on the problem.
> Seems like `${XDG_CONFIG_HOME}` or `${XDG_DATA_HOME}` are not evaluated in the trellowarrior conf, might just be this.

In this case the UDAs are not defined and the results may be unexpected

**Comment by nicolas-graves** [comment]
So I replaced with literal values : `~/.config/task/taskrc` and `~/.local/share/task/`. 
Everything seems to work fine now. 
Thanks a lot !
