### ISSUE TITLE
[low priority] `sync_projects` and `sync_project` ambiguity or a parsing bug when quoting a string

### ISSUE THREAD

**Issue by DDzwiedziu** [ogarcia/trellowarrior#32]
It's not a high priority, as it a PEBKAC, still shows how one can make a mistake. If discussions were enabled I'd wouldn't make an issue out of this. Especially that I've just made the same mistake as in #21. Still there could be an issue with quoting a string.

As far as I see in the docs and in the code the configuration stanza is `sync_projects` (ending with a “s”). Yet if I quote the string:
```
❯ grep '^sync' ~/.config/trellowarrior/trellowarrior.conf
sync_projects = 'project_name'
❯ trellowarrior -v sync
INFO:TrelloWarrior:Setting loglevel to INFO
Traceback (most recent call last):
  File "/home/dzwiedziu/.local/bin/trellowarrior", line 8, in <module>
    sys.exit(main())
  File "/home/dzwiedziu/.local/lib/python3.10/site-packages/trellowarrior/main.py", line 128, in main
    config.configure(config_file=args.config, projects=args.projects)
  File "/home/dzwiedziu/.local/lib/python3.10/site-packages/trellowarrior/config.py", line 129, in configure
    logger.warning('Missing config section for sync project \'{}\', ignoring it'.format(sync_project))
NameError: name 'sync_project' is not defined
```

...so I've changed to `sync_project`:
```
❯ sed -i -e 's/^sync_projects/sync_project/' ~/.config/trellowarrior/trellowarrior.conf
❯ grep '^sync' ~/.config/trellowarrior/trellowarrior.conf
sync_project = 'project_name'
❯ trellowarrior -v sync
INFO:TrelloWarrior:Setting loglevel to INFO
No projects to sync
```
This made me search the docs and code again, as I was overthinking what can be the issue. AFAIK now trellowarrior did exactly what it was coded for – no `sync_projects`, no sync.

The fix? Remove apostrophes from `sync_projects`:
```
❯ grep '^sync' ~/.config/trellowarrior/trellowarrior.conf
sync_projects = project_name
❯ trellowarrior -v sync
INFO:TrelloWarrior:Setting loglevel to INFO
INFO:trellowarrior.clients.trellowarrior:Syncing project project_name step 1: delete Trello cards that already deleted in Taskwarrior
INFO:trellowarrior.clients.trellowarrior:Syncing project project_name step 2: syncing changes between Taskwarrior and Trello
INFO:trellowarrior.clients.trellowarrior:Syncing project project_name step 3: delete Takswarrior tasks that already deleted in Trello
INFO:trellowarrior.clients.trellowarrior:Syncing project project_name step 4: upload new Takswarrior tasks
INFO:trellowarrior.clients.trellowarrior:Project project_name synchronized
```

**Comment by ogarcia** [comment]
The question is, why did you put quotation marks around it? In the example configuration file there are no quotation marks. In fact, it clearly says:
```
# Set what projects are active and sync (separated by spaces)
sync_projects = connectical personal
```

In fact, you get the error because it is looking for a section called `['project_name']` (literally with the quotation marks).

In any case, if you have found a bug in the line:
```python
logger.warning('Missing config section for sync project \'{}\', ignoring it'.format(sync_project))
```
It should be `project` instead of `sync_project`. So that instead of giving you that error it would say:
```
Missing config section for sync project ''project_name'', ignoring it
```

When you have changed `sync_projects` to `sync_project`, what you have really done is not declare `sync_projects` and invent a new key that the system simply ignores. It makes no difference whether you put `sync_project` or `popcorn`. :wink:
