### ISSUE TITLE
Py-Trello has authentication issues after a recent Trello change

### ISSUE THREAD

**Issue by aboudaty** [ogarcia/trellowarrior#34]
The original py-trello is not working anymore. It has been broken for about 6 weeks. Please consider using this temporary fix mentioned by @Konano at the end of [this issue](https://github.com/sarumont/py-trello/issues/376#issue-2218799609).

**Comment by aboudaty** [comment]
https://github.com/sarumont/py-trello/issues/376#issuecomment-2031572791

**Comment by ogarcia** [comment]
Thanks @aboudaty for the heads up. I prefer to be cautious and wait to see what happens with py-trello before switching to a fork, but we'll leave this issue open.

For all those who have problems at this time, simply edit the `requirements.txt` file and replace `py-trello` with `py-trello-api==0.20.0`. Here is the complete file:

```
py-trello-api==0.20.0
requests
tasklib
```
