### ISSUE TITLE
Trellowarrior finds closed boards

### ISSUE THREAD

**Issue by jean** [ogarcia/trellowarrior#5]
## To reproduce
- Create _Board A_
- Close _Board A_
- Create another _Board A_
- Add a task to the trellowarrior project with `trello_board_name` set to _Board A_  
### What I see

The card is added to the closed board.
### What I expect to see

The card is added to the new open board.

**Comment by ogarcia** [comment]
I suggest an easy workaround that simply rename closed board form _Board A_ to _Board A (Closed)_.

**Comment by ogarcia** [comment]
Shit, the bug is in [get_trello_board function](../blob/master/trellowarrior.py#L87).

Mmm, I need to reread the py-trello library to know if there is a method to get board status and ignore the closed ones...
