### ISSUE TITLE
Apply a cookiecutter template

### ISSUE THREAD

**Issue by jean** [ogarcia/trellowarrior#6]
Just as a heads-up: I'm in the process of applying [cookiecutter](https://github.com/audreyr/cookiecutter) to trellowarrior.
This adds a bunch of goodies like support for Sphinx docs, Travis CI, pytest, and the Click CLI framework.

At the moment this is mostly just a whole lot of stubs. Here's the [big diff](https://github.com/ogarcia/trellowarrior/compare/master...jean:master). 
(It includes some tweaks to trellowarrior conf parsing which should be considered separately.)

I just wanted to mention it to check if you think it's a worthwhile idea.

**Comment by ogarcia** [comment]
Yes, is a good idea!! I had thought to package it a while ago, but the days only have 24 hours. :wink: 

I look the changes and the only thing that I would change is the use of Click as argument parser. The app has not arguments and i think that use Click is like kill flies with nuclear bombs. :joy: :joy:

For arguments I would use the python argument parser to have less requirements.

**Comment by jean** [comment]
Hmm good point on Click, I'll revisit that. 
I might **add** some arguments .. 

- we have many boards, and it would be useful to me to specify boards on the commandline rather than editing a config file. 
- I'd like some kind of `dry-run` and `download-only` options (I'm nervous about accidental batch changes to Trello).
- I'd also like to be able to specify a config file location.
- some usual options like `-h`, `--version`, `--verbose` (log at `info` level?).

**Comment by ogarcia** [comment]
For `verbose` can use `count` in [argparse](https://docs.python.org/3.6/library/argparse.html#action). So `-v` can be `info` and `-vv` can be `debug`.

**Comment by ssbarnea** [comment]
Any update on this? Having it published as a python module would be highly desired.
